### PR TITLE
Modify the install script to be able to work with our flake setup.

### PR DESCRIPTION
**Pull request by R-VdP**
Adapt to the changes in MSF-OCB/NixOS-OCB#123.

Ping @ianso-msf @XKa-MSF-OCB

### CODE REVIEW

**Comment by XKa-MSF-OCB** [comment]
@R-VdP 

Shouldn't command `nix-channel --update` be removed from script `install.sh`, as we are moving to Nix flakes?
https://github.com/MSF-OCB/NixOS-OCB-install/pull/2/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR523

Would any other commands still need be added/adapted/removed in this script?

**Comment by R-VdP** [comment]
> @R-VdP
> 
> Shouldn't command `nix-channel --update` be removed from script `install.sh`, as we are moving to Nix flakes? https://github.com/MSF-OCB/NixOS-OCB-install/pull/2/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR523
> 
> Would any other commands still need be added/adapted/removed in this script?

True, done.

For testing, please feel free.

**Comment by R-VdP** [comment]
@XKa-MSF-OCB the last commit doesn't actually belong in this PR, it would be better to put it in its own PR, since the changes are unrelated.

**Comment by R-VdP** [comment]
@XKa-MSF-OCB since this is a feature branch, you don't need to revert, you can rewrite history.

First write down the commit hash of the commit that you want to make a separate PR for, you'll need it below.

Now you want to remove the last two commits from this branch by doing 
```
git reset --hard HEAD~2
git push --force-with-lease
```

Then make a new branch based on `main` and cherry pick the commit you wanted
```
git switch main
git switch -c <name>
git cherry-pick <commit hash>
```

**Comment by XKa-MSF-OCB** [comment]
@R-VdP 
Many thanks for the detailed explanations.
I had already tried to create a new branch and push to it, but it fails, I guess because this is your own fork of the repo:
```
To github.com:R-VdP/NixOS-OCB-install.git
 ! [remote rejected] XKa/improve_install_script_20230630a -> XKa/improve_install_script_20230630a (permission denied)
error: failed to push some refs to 'github.com:R-VdP/NixOS-OCB-install.git'
```

**Comment by R-VdP** [comment]
Don't push the new branch to this fork, push it to this repo. You need to set the branch to track the correct remote.

**Comment by R-VdP** [comment]
See #3.

**Pull request closed without merging**
